name: vr_player
description: A VR/360 Player For Flutter

publish_to: "none"

version: 1.0.0+10

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.3.2

flutter:
  uses-material-design: true
